server:
  port: 8082

spring:
  application:
    name: auth-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: "postgres"
    password: "yourPassword"

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

logging:
  level:
    org.springframework.web: info