server:
  port: 8081

spring:
  application:
    name: student-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: "postgres"
    password: "password"

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411
  tracing:
    sampling:
      probability: 1.0