server:
  port: 8081

spring:
  application:
    name: student-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://postgres:5432/student
    username: "postgres"
    password: "password"

eureka:
  client:
    service-url:
      defaultZone : http://eureka:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0